ALTER TABLE pitches
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'SUBMITTED'
    CHECK (status IN ('DRAFT', 'SUBMITTED', 'ARCHIVED')),
  ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_pitches_status ON pitches (status);